version: '3'
services:
  hyperf-admin:
    container_name: hyperf-admin
    image: hyperf-admin
    build:
      context: .
    volumes:
      - ./:/opt/www
    entrypoint: ['php', 'watch', '-c']
    ports:
      - 9501:9501
    environment:
      - APP_ENV=dev
      - SCAN_CACHEABLE=false

networks:
  default:
    name: hyperf-admin
